log:
  # 控制台日志参数
  enableConsole: true
  consoleJSONFormat: true
  consoleLevel: Debug
  # 文件日志参数
  enableFile: true
  fileJSONFormat: false
  fileLevel: Debug
  fileLocation: /home/www-data/logs/base-log.log
  maxAge: 28 # 最大天数
  maxSize: 100 # 文件最大容量
  compress: true # 是否压缩
  fileExport: /home/www-data/logs

webapi:
  uri: 0.0.0.0:8080

mysqlnd:
  username: root
  password: 123123
  host: 127.0.0.1
  port: 3306
  database: kcm

